name: Deploy SEO Crawler Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Run Linter
      run: npm run lint
    
    - name: Run Tests
      run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Deploy to Server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        # Install sshpass for password-based SSH
        sudo apt-get update
        sudo apt-get install -y sshpass
        
        # Sync project files
        sshpass -p "$SERVER_PASSWORD" rsync -avz \
          --exclude='node_modules' \
          --exclude='.git' \
          --exclude='.env' \
          . $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH
        
        # Run remote commands without sudo
        sshpass -p "$SERVER_PASSWORD" ssh $SERVER_USER@$SERVER_HOST << EOF
          # Navigate to project directory
          cd $DEPLOY_PATH
          
          # Use local Node.js and npm
          export PATH=$HOME/.npm-global/bin:$PATH
          
          # Install dependencies
          npm install
          
          # Stop existing process
          npx pm2 delete seo-crawler || true
          
          # Start new process
          npx pm2 start server.js --name seo-crawler
          
          # Save PM2 process list
          npx pm2 save
        EOF